[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"

[phases.frontend]
cmds = [
    "cd frontend",
    "npm install",
    "npm run build"
]

[phases.backend]
cmds = [
    "cd backend",
    "pip install -r requirements.txt"
]

[env]
PYTHON_VERSION = "3.11"
PORT = "8000"
FRONTEND_URL = "http://localhost:3000"
